#!/usr/bin/env bash
#
# Delete the "guest" default user and replace it with a Zulip user
# with a real password
set -e
set -x

# Check for a supported OS release.
if [ -f /etc/os-release ]; then
    os_info="$(
        . /etc/os-release
        printf '%s\n' "$ID" "$ID_LIKE" "$VERSION_ID" "$VERSION_CODENAME"
    )"
    {
        read -r os_id
        read -r os_id_like
        read -r os_version_id
        read -r os_version_codename || true
    } <<<"$os_info"
    case " $os_id $os_id_like " in
        *' debian '*)
            package_system="apt"
            ;;
        *' rhel '*)
            package_system="yum"
            ;;
    esac
fi

if [ "$EUID" -eq 0 ]; then
    rabbitmqctl=(rabbitmqctl)
else
    rabbitmqctl=(sudo rabbitmqctl)
fi

if [ -n "$RABBITMQ_NODE" ]; then
    rabbitmqctl+=(-n "$RABBITMQ_NODE")
fi
RABBITMQ_USERNAME=$("$(dirname "$0")/../get-django-setting" RABBITMQ_USERNAME)
RABBITMQ_PASSWORD=$("$(dirname "$0")/../get-django-setting" RABBITMQ_PASSWORD)

# Force a known locale.  Some packages on PyPI fail to install in some locales.
if [ "$os_id" = centos ]; then

    # Wait for RabbitMQ to start up
    try_ping() {
        # `rabbitmqctl ping` requires 3.7.6 or newer
        out="$("${rabbitmqctl[@]}" eval 'net_adm:ping(node()).')" && [[ "$out" == *"pong"* ]]
    }
    retries=9
    while ! try_ping 2>/dev/null; do
        sleep 1
        if ! ((retries -= 1)); then
            try_ping
            break
        fi
    done

else

    # Wait for RabbitMQ to start up
    try_ping() {
        # `rabbitmqctl ping` requires 3.7.6 or newer
        out="$("${rabbitmqctl[@]}" eval 'net_adm:ping(node()).')" && [ "$out" = 'pong' ]
    }
    retries=9
    while ! try_ping 2>/dev/null; do
        sleep 1
        if ! ((retries -= 1)); then
            try_ping
            break
        fi
    done

fi

"${rabbitmqctl[@]}" delete_user "$RABBITMQ_USERNAME" || true
"${rabbitmqctl[@]}" delete_user zulip || true
"${rabbitmqctl[@]}" delete_user guest || true
"${rabbitmqctl[@]}" add_user "$RABBITMQ_USERNAME" "$RABBITMQ_PASSWORD"
"${rabbitmqctl[@]}" set_user_tags "$RABBITMQ_USERNAME" administrator
"${rabbitmqctl[@]}" set_permissions -p / "$RABBITMQ_USERNAME" '.*' '.*' '.*'